IF OBJECT_ID('dbo.[FK_Item_Z_TypeItem4]', 'C') IS  NULL 
    --ALTER TABLE dbo.[ITEM] DROP CONSTRAINT FK_Item_Z_TypeItem4
    --ALTER TABLE dbo.[ITEM] DROP CONSTRAINT FK_Item_Z_TypeItem5
    --ALTER TABLE dbo.[ITEM] DROP CONSTRAINT FK_Item_Z_TypeItem6
    --ALTER TABLE dbo.[ITEM] DROP CONSTRAINT FK_Item_Z_TypeItem7
BEGIN
 
 BEGIN  TRY
  BEGIN TRANSACTION
ALTER TABLE [dbo].[Item]  WITH NOCHECK ADD  CONSTRAINT [FK_Item_Z_TypeItem4] FOREIGN KEY([IdTypeItem4])
REFERENCES [dbo].[Z_TypeItem4] ([id])
ON UPDATE CASCADE

ALTER TABLE [dbo].[Item] NOCHECK CONSTRAINT [FK_Item_Z_TypeItem4]


ALTER TABLE [dbo].[Item]  WITH NOCHECK ADD  CONSTRAINT [FK_Item_Z_TypeItem5] FOREIGN KEY([IdTypeItem5])
REFERENCES [dbo].[Z_TypeItem5] ([id])
ON UPDATE CASCADE


ALTER TABLE [dbo].[Item] NOCHECK CONSTRAINT [FK_Item_Z_TypeItem5]


ALTER TABLE [dbo].[Item]  WITH NOCHECK ADD  CONSTRAINT [FK_Item_Z_TypeItem6] FOREIGN KEY([IdTypeItem6])
REFERENCES [dbo].[Z_TypeItem6] ([id])
ON UPDATE CASCADE


ALTER TABLE [dbo].[Item] NOCHECK CONSTRAINT [FK_Item_Z_TypeItem6]


ALTER TABLE [dbo].[Item]  WITH NOCHECK ADD  CONSTRAINT [FK_Item_Z_TypeItem7] FOREIGN KEY([IdTypeItem7])
REFERENCES [dbo].[Z_TypeItem7] ([id])
ON UPDATE CASCADE


ALTER TABLE [dbo].[Item] NOCHECK CONSTRAINT [FK_Item_Z_TypeItem7]
 COMMIT TRANSACTION
 END TRY
    BEGIN CATCH
                 ROLLBACK TRANSACTION
                 SELECT ERROR_MESSAGE() 
    END CATCH
END