IF OBJECT_ID (N'EmpTypeSalary', N'U') IS NULL 
BEGIN
CREATE TABLE [dbo].[EmpTypeSalary](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[type] [nvarchar](100) NOT NULL,
	[IsAdd] [int] NOT NULL,
 CONSTRAINT [PK_EmpTypeSalary] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

end


