
IF OBJECT_ID (N'Z_delegate', N'U') IS NULL 
BEGIN
CREATE TABLE [dbo].[Z_delegate](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[aname] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Z_delegate] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END


