IF OBJECT_ID (N'zzz_DirectEx', N'U') IS NULL 
BEGIN

CREATE TABLE [dbo].[zzz_DirectEx](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[aname] [nvarchar](80) NOT NULL,
 CONSTRAINT [PK_p_DirectEx] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END


