IF OBJECT_ID (N'z_news', N'U') IS NULL 
BEGIN

CREATE TABLE [dbo].[z_news](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[aname] [nvarchar](200) NULL,
 CONSTRAINT [PK_z_news] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

end


