IF OBJECT_ID (N'Z_PurExpenses', N'U') IS NULL 
BEGIN

CREATE TABLE [dbo].[Z_PurExpenses](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[aname] [nvarchar](50) NULL,
 CONSTRAINT [PK_PurExpenses] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

end


