IF OBJECT_ID (N'Z_Service', N'U') IS NULL 
BEGIN
CREATE TABLE [dbo].[Z_Service](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[Aname] [nvarchar](100) NULL,
	[Cost] [float] NULL,
 CONSTRAINT [PK_Z_Service] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END


