IF OBJECT_ID (N'Z_TypeItem7', N'U') IS NULL 
BEGIN
CREATE TABLE [dbo].[Z_TypeItem7](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[aname] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Z_TypeItem7] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

end


